### ISSUE TITLE
Why don't you predict the contact force directly?

### ISSUE THREAD

**Issue by hdadong** [CLeARoboticsLab/ssrl#2]
@jake-levy @Why don't you predict the contact force directly, since that would make use of Jacobian's information? You could predict the contact force directly and remove the parasitic damping torques from the Equation (1) in your paper, and attribute all external uncertainties to the contact force, Wondering why you didn't do this.

**Comment by jake-levy** [comment]
During the initial stages of this project, we found that predicting contact forces $F^e$ directly resulted in worse performance.

**Comment by hdadong** [comment]
Thank you for your reply. What are the possible reasons for getting worse performance? Intuitively, introducing Jacobian will make the predicted force more consistent with physics

**Comment by jake-levy** [comment]
Joint damping forces and forces from things like higher-order actuator dynamics act directly on the joints -- if we try to predict these in the world coordinates, the neural network essentially has to learn a transformation from the joint to the world coordinates, only to have its prediction converted back to the joint coordinates. I think these extra steps are what made it worse. I think the higher-order actuator dynamics introduced some delay in joint actuation and having the network directly predict in the joint coordinates allowed it to directly make additive corrections to the estimated applied torque obtained from the PD control law. Also, by not having to compute the Jacobians, we save on a little bit of computation time.

**Comment by hdadong** [comment]
Thank you for your insightful response. It is indeed challenging for a neural network to learn the transformation from joint to world coordinates.
